### ISSUE TITLE
Using the Opus Decoder in an Audio Worklet

### ISSUE THREAD

**Issue by spacehash** [eshaz/wasm-audio-decoders#107]
I'm building a UI in React, and instantiating an audio worklet with the following block.

`audioContext.audioWorklet.addModule(workletURL).then(() => { ... }`

I can use the decoder in react via the following block.

```
decoder.ready.then(() => {
    decoder.decodeFrame(base64DecodedOpusFrame).then((opusStructure) => { ... }
});
```

This works just fine, and I'm able to send the resulting `opusStructure.channelData` to the worklet and play audio. However, I would like to do this decoding step in the worklet thread, and I can't seem to figure out how to do so. I can import any other npm js package in the worklet.js file via something like the following.

`import { package } from "package"`

But when I try to do the following, execution stops on that import. 

`import {OpusDecoder} from "opus-decoder"`

I'm unsure how to give a more verbose error explanation, as I'm not sure how to extract that info from a javascript Audio Worklet. Any help would be greatly appreciated.

**Comment by eshaz** [comment]
I'm not sure `import` will work at all within an AudioWorklet, depending on how the React app is being built. I believe the AudioWorklet will execute within it's own environment, and won't have access to any of the code defined outside of it, which would include any bundler code that handles the `import` statement.

There is `OpusDecoderWebWorker` that executes in a web worker thread, which will accomplish the same multi-threading that running the decoder within an AudioWorklet would. I would recommend using that if you need concurrency. You can decode the Opus data in small chunks if needed by passing the data into the `decode` method. It will return chunks of audio that can be immediately played in sequence or piped into another AudioWorklet for additional processing.

You might try debugging the worklet with the browser debugger, if you want to continue with that option.

**Comment by spacehash** [comment]
I'm not sure why I didn't infer, from the name, OpusDecoderWebWorker is a web worker, and as such executes in it's own thread :D. Playing audio in its decode method is trivial and suits my needs. Thank you for your quick response!

**Comment by adam-kiss-sg** [comment]
Hi!

I ran into the same problem. I'm using OpusDecoder in an AudioWorklet: 
```
import { OpusDecoder } from 'https://cdn.jsdelivr.net/npm/opus-decoder@0.7.11/+esm';
```

It works, but requires a bit of a workaround: I have a polyfill.js with the following:
```
// required by opus decoder
globalThis.Worker = class Worker {};
```

So, the import statement fails because there is no global Worker class defined in the AudioWorklet context. Other than that, the decoding works perfectly in AudioWorklet.

Some more info of why someone would want to do the decoding in an AudioWorklet instead of a WebWorker: I'm working on a rust WASM base jitter buffer to keep the latency minimal (not my project, I'm just contributing to it: https://github.com/security-union/videocall-rs/tree/main/neteq/). This uses opus-decoder to decode the audio. The decoding and the buffer both work very well, but I run into a trouble when I tried to play back the audio: there is no reliable way to get the audio from the worker to the AudioWorklet fast enough (under 10-20ms). So I decided to try moving the whole processing to the AudioWorklet instead.

@eshaz would you consider re-opening this issue? I think the fix is quite straightforward (adding a check if Worker is defined).
