### ISSUE TITLE
opus-decoder "Demo" doesn't demo opus-decoder

### ISSUE THREAD

**Issue by EricTetz** [eshaz/wasm-audio-decoders#49]
Kinda nitpicky, but caused me a little pain. The "Demo" link  on the [opus-decoder page](https://github.com/eshaz/wasm-audio-decoders/tree/master/src/opus-decoder) leads to a demo of ogg-opus-decoder, which is _not_ the same thing. In particular, it doesn't support multichannel decoding, which is the one thing I wanted to test of opus-decoder.

**Comment by eshaz** [comment]
Both ogg-opus-decoder and opus-decoder support multichannel decoding. You can even playback a multichannel ogg opus file in the demo web page after decoding, if you have a multichannel soundcard. See the readme on each library for more details on how many channels are supported.

I didn't add opus-decoder to the demo since there's no file format I'm aware of that uses raw opus frames. If you have an example of this, or a suggestion on how to add that to the demo I'll take that into consideration.

**Comment by EricTetz** [comment]
> Both ogg-opus-decoder and opus-decoder support multichannel decoding.

Yes, but not to the same extent. 

![image](https://user-images.githubusercontent.com/929211/180384792-a762ccb5-f4c8-4f58-b8cb-eef06749c0bb.png)

My particular use case is streaming a 16 channel live recording of my band (sometimes 32 channel). The ogg-opus-decoder demo barfs on it. I have 16 channel rehearsal/gig recordings that are 3-4 hours long, so loading them in their entirety before playback is a non-starter. My plan is to efficiently stream multichannel recordings to an online mixer for my bandmates to review.

> I didn't add opus-decoder to the demo since there's no file format I'm aware of that uses raw opus frames. If you have an example of this, or a suggestion on how to add that to the demo I'll take that into consideration.

Well, it would require more work on your part, but you'd need to arrange to deliver yourself some raw opus frames, so you can demonstrate decoding them. It doesn't make much sense to link from [the opus-decoder page](https://github.com/eshaz/wasm-audio-decoders/tree/master/src/opus-decoder) to something that demonstrates a different decoder.

There's some code [here](https://github.com/AnthumChris/fetch-stream-audio/blob/master/utils/opus-file-splitter/src/OpusFileSplitter.mjs) that I'm planning to use to get some raw opus frames, but I'm not on my dev machine at the moment. Have to try that in the morning.

**Comment by EricTetz** [comment]
> Was it Ogg Opus?

Yup.

> Are you sure you would be sending in raw Opus frames in your application? 

That would be ideal for my use, right? I've got 1 day of looking into this under my belt, so I don't have a great grasp of it yet. My understanding is that Ogg is just a container format. Within it are the Opus frames. Are those individual frames "raw Opus frames", or is that something else? The point is that my app would be continually requesting individual frames or ranges of frames to decode and feed to the mixer.

>  It would be up to the user to send in a file containing only raw Opus frames.

But doesn't the decoder need to be fed one frame at a time? How would you know where those frames are in the file the user uploads, if they're not in some known format (e.g. ogg)?

>  If you have an example file I could test with that would be great if you could send that along.

[Here you go.](https://github.com/eshaz/wasm-audio-decoders/files/9169631/Multichannel.zip) ffprobe output:

  Input #0, ogg, from 'Multichannel.opus':
    Duration: 00:00:11.21, start: 0.000000, bitrate: 1873 kb/s
      Stream #0:0: Audio: opus, 48000 Hz, 16 channels, fltp

**Comment by eshaz** [comment]
> My understanding is that Ogg is just a container format. Within it are the Opus frames.

Yes, Ogg is a container format, and Opus is a codec. Ogg Opus just means that the container format is Ogg and stored within it are the raw Opus frames. Ogg is commonly used to contain other codecs such as Vorbis and FLAC. Ogg's purpose is mainly to add additional metadata and timing information to the raw codec data.

> But doesn't the decoder need to be fed one frame at a time? How would you know where those frames are in the file the user uploads, if they're not in some known format (e.g. ogg)?

You're right about this. I suppose it's not explicitly mentioned in the docs, but `opus-decoder` is really intended for a user that has already extracted the data from whatever container they have. Ogg is by far the most common container for Opus, but other container types can store Opus as well, such as ISOBMFF (.mp4) and Mastroka / WEBM (.mkv). I'll add that point to the documentation so it's more clear.

I'm going to take a look at the implementation in `ogg-opus-decoder` and try to swap out `opusfile` with a combination of my other library [`codec-parser`](https://github.com/eshaz/codec-parser) (to extract the Opus frames) and `opus-decoder` (to decode the frames). This should allow all 255 possible channels to be decoded through `ogg-opus-decoder`. I'll make sure it works against that test file you sent.

To-do on my side:

- [ ] `ogg-opus-decoder` Swap out `opusfile` for `codec-parser` / `opus-decoder`
- [ ] `opus-decoder` Add additional usage note in readme on containers vs. codec frames

I was thinking about your use-case some more, you might be better off encoding your multi-track audio beforehand into small chunks of Ogg Opus data that are split on a known time range, like every 5 seconds or something. Then your client side code could request whatever time range is required to play at any given point. These files could be fed into `ogg-opus-decoder` and decoded to the multi channel PCM. I don't think you would even need any special code to run on your backend, you could use GET requests and serve these chunks up via a basic HTTP server, assuming you've already encoded the chunks beforehand.

**Comment by EricTetz** [comment]
> If you don't mind, I could add the test file into this repo

It's not mine, but should be covered by Fair Use (technical use clause). It's a few seconds of _Never Gonna Give You Up_. ;)

> I was thinking about your use-case some more, you might be better off encoding your multi-track audio beforehand into small chunks of Ogg Opus data that are split on a known time range, like every 5 seconds or something.

I'm still considering that option. It might have advantages.

The recordings are in ~22 minute chunks (4 GB PCM, 330 MB Opus), or ~11 minute chunks for 32 channel. For a 4 hour show, I'm looking at 11-22 files. With 5 second chunks, that becomes 2880-5760 files, *per* show, and we do a lot of shows. That feels like a pain in the butt.

I like the idea of `opus-decoder` aesthetically, because I'll have thousands of audio pages, each with the exact same header. It would be nice to parse the header once and only once, then decode an arbitrary number of pages using those settings.

If I have to use the `ogg-opus-decoder`, I could just add the header back to each audio page. That's what [this tool](https://github.com/AnthumChris/fetch-stream-audio/blob/master/utils/opus-file-splitter/src/OpusFileSplitter.mjs) does to split Opus files. It parses the header once, then cycles through the audio pages and appends the same header to each.

Of course, if I'm parsing using Ogg Opus data, then `ogg-opus-decoder` is just for Safari support, right? The browser's `decodeAudioData` can decode Ogg Opus in [other browsers](https://caniuse.com/?search=opus).

My server could send back Ogg Opus chunks, or I could send the header once at the start of the session, then just append the header to each packet on the client. But again, it would be aesthetically preferable to not have to do that, to have whatever configuration information the decoder gets from the header done once, then I just feed it raw pages for decoding. Less work on the client.

**Comment by eshaz** [comment]
I've released [`ogg-opus-decoder/1.4.0`](https://github.com/eshaz/wasm-audio-decoders/releases/tag/ogg-opus-decoder%2F1.4.0) which adds support for up to 255 channels of multichannel decoding, and also updated the demo with this latest version. You can try your test files in the demo and it will decode all of the channels. If you want to verify, there is an option to download the decoded audio, which will generate a multichannel wave file.

> Of course, if I'm parsing using Ogg Opus data, then ogg-opus-decoder is just for Safari support, right? The browser's decodeAudioData can decode Ogg Opus in [other browsers](https://caniuse.com/?search=opus).

It depends on your use-case. `decodeAudioData` only supports decoding entire files, and I'm not sure if it supports multichannel. The libraries in this repo support decoding small chunks at a time, which is required when decoding streaming audio, or if you want to create a pipeline that decodes while the data is still being received, such as decoding from the result of an ongoing fetch request. You could fetch a very large file and decode / play it in chunks without having to use up a bunch of memory or wait for the entire file to download.

> My server could send back Ogg Opus chunks, or I could send the header once at the start of the session, then just append the header to each packet on the client. But again, it would be aesthetically preferable to not have to do that, to have whatever configuration information the decoder gets from the header done once, then I just feed it raw pages for decoding. Less work on the client.

It's actually not that much work on the client to parse the Ogg pages, and adds virtually no time compared to the time taken decoding. Personally, I would just encode the chunks beforehand using ffmpeg, `fetch` on the client as needed, and pipe the response's [`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) into `OggOpusDecoderWebWorker.decode()` to keep things simple. (If you do this, you will also need to call `flush()` at the end of the request to decode the rest of the frames that are still in the decoder's buffer.)

I'm going to close this issue since `ogg-opus-decoder` now supports the full 255 channels. Either of the Opus decoder libraries should work for you.

Good luck with your app!

Also, is that the actual multi-track master of that song, or did you / your band put that together?
