### ISSUE TITLE
catch promise resolve on decodeFrames

### ISSUE THREAD

**Issue by jjackevans** [eshaz/wasm-audio-decoders#60]
Hi,

When errors are thrown, the `.catch()` promise doesn't get resolved.
Let me know if you need any more details to reproduce or if this is what you'd expect.

Thanks

**Comment by eshaz** [comment]
Could you provide an example?

If there is an error with the input data, the decoder should attempt to decode everything possible, log an error, return any results if they exist, and continue to decode future audio.

**Comment by jjackevans** [comment]
Ok, I think the issue is that 

```
decoder.decodeFrames(frames)
    .then(result => {
        // do something with result
        decoder.free()})
    .catch(e => console.log("This is never called"))
```

There doesn't seem to be a way to handle an error. When frames fail to be decoded, it won't even enter the `.then()` block where I could detect if there are frames missing.

Is there any way I could handle the error?

**Comment by eshaz** [comment]
Are you still using `opus-decoder`, like you asked about in your previous issue? Let me know, and I'll take a look.

**Comment by jjackevans** [comment]
Yup.. and the webworker implementation. 
Thanks 👍

**Comment by eshaz** [comment]
@jjackevans I added a few changes in opus-decoder/0.6.0 so that any errors that show up during decoding will be returned in the decoded data `error` object.

See the new API for this here:
https://github.com/eshaz/wasm-audio-decoders/tree/master/src/opus-decoder#api

This should allow you to continue decoding through errors, and know what data relative to frame number, input bytes, and output samples that are lost due to any errors. Let me know if this works for you!
