### ISSUE TITLE
Error when using OpusAudioDecoder to decode a single file in Electron

### ISSUE THREAD

**Issue by ogomez92** [eshaz/wasm-audio-decoders#63]
Environment: Electron 17.0.1, renderer process, with nodeIntegrationInWorker: true

I have found an issue trying to decode an Opus file using OggOpusDecoderWebWorker.
I am getting the error as follows:

```
TypeError: Cannot read properties of null (reading 'decodeFrames')
```

I only need to decode a single file, so I am sing await (I know it is a bad idea, I have read the best practices guide in the docs).

```Typescript
import { OggOpusDecoder, OggOpusDecoderWebWorker } from 'ogg-opus-decoder';
class ... {

    public decode = async (path: string): Promise<AudioBuffer> => {
        try {
            const decoder = new OggOpusDecoderWebWorker();
            await decoder.ready;

            let response = await fs.readFileSync(path);

            const { channelData, samplesDecoded, sampleRate } = await decoder.decodeFile(new Uint8Array(response));
            response = null;
            const buffer = this.context.createBuffer(channelData.length, samplesDecoded, sampleRate);

            channelData.map((channel, index) => {
                buffer.copyToChannel(channel, index);
            });

            decoder.free();

            return buffer;
        } catch (error) {
            throw new Error(`opus decoder was unable to decode the file at ${path}: ${error}`)
        }
    }
}
```

Curiously OggOpusDecoder (without the web worker) works fine.

I am running into a similar issue with the mpeg decoder web worker (works without the worker), saying that URL scheme must be of type file, but I can open another issue if needed, maybe it's something in Electron's part or I am doing something wrong so I think one issue will suffice for now?

Thanks for your assistance.

**Comment by eshaz** [comment]
I've never tried running this library in Electron, but I think it should work fine, since Electron is just a browser under the hood.

Could you post the full stack traces so I can see where in the decoders those errors are being thrown? Also, do you have a repo I can clone down so I can reproduce the error? I might have to experiment with some solutions on this.

I have a couple things you can try in the meantime:

Could you try setting `nodeIntegrationInWorker: true` to `false`? This might be causing an issue with how ogg-opus-decoder detects if it's running in a browser or NodeJS.

I recently made a change in how the web workers are implemented in this library. Could you try ogg-opus-decoder/1.4.4 and see if version also has the errors?

**Comment by ogomez92** [comment]
Hello,
Here's the stack from version 1.5.0.

C:\Users\ogome\code\leveltool\stest\peli.opus: TypeError: Cannot read
properties of null (reading 'decodeFrames')
    at DecoderState._sendToDecoder (OggOpusDecoder.js:38:1)
    at DecoderState._decode (

Version 1.4.4 fails with the same stack trace.

Yes, you can find a repo here. And thanks much for looking into this!
Just do yarn && yarn dev

This has some additional stuff but what you want is in
src/lib/sound/decoders/. Main.ts expects a file in
__dirname/peli.opus.
https://github.com/ogomez92/rhythm_rage_level_helper_tool

Thanks.

**Comment by ogomez92** [comment]
also, changing nodeIntegrationInWorker didn't change the behaviour.

**Comment by eshaz** [comment]
Thanks for that additional info. I think I found the problem and will be releasing a fix here soon.

**Comment by eshaz** [comment]
Go ahead and try out `ogg-opus-decoder/1.5.1`. I was able to get it working with your repo locally. I've also bumped the other decoders, and that should resolve the problem with the worker on those as well. Let me know if it works for you!

**Comment by ogomez92** [comment]
Thanks, I'll check it out. Just curious, was the issue web worker
specific or is it because of the Electron environment? I'm guessing
Electron has some weird processing with webworkers? I don't have much
experience with WASM other than using it in js.

Thanks!

**Comment by eshaz** [comment]
I think the issue was probably in your build pipeline. I am using a `web-worker` library that allows for the browser `Worker` api to be used in NodeJS. Depending on the bundling toolset used, the NodeJS version can be selected by mistake which was the problem you were facing.

This conditional on line 4 below fixes the problem by extending `WASMAudioDecoderWorker` with `Worker` if it exists, otherwise it's extended with the NodeJS polyfill.

https://github.com/eshaz/wasm-audio-decoders/blob/598abd116e54fb4593b7f2f4ab3163d782fe9e85/src/common/src/WASMAudioDecoderWorker.js#L1-L6

There might be a configuration option in the bundling tool your using, webpack I think, that fixes this too, but it seems like a common problem. Fixing this here should make this library simpler to use.
